import { PARAM_DESCRIPTIONS } from './statusDescriptions'

/**
 * Display names for effect parameters.
 *
 * The registry labels in effectParams.ts are short caps codes (SCTR, DPTH, RFSH...). They stay as they are
 * (presets, p-locks and descriptions may key on them); everything the user reads goes through
 * displayParamLabel(), resolved in this order:
 *   1. PARAM_NAME_OVERRIDES[`${effectId}.${param.id}`]  (codes whose meaning depends on the effect)
 *   2. ABBREVIATIONS[param.label]                       (shared dictionary)
 *   3. the humanised param id                           (noiseSpeed -> "Noise speed")
 *   4. the label in sentence case                       (MASK VIEW -> "Mask view")
 * Names are sentence case. `short: true` gives a name of about 10 characters for the 50px device dials.
 */

/** Shared code -> name dictionary, for codes that mean the same thing in every effect that uses them. */
export const ABBREVIATIONS: Record<string, string> = {
  ACC: 'Accumulation',
  AGE: 'Age',
  AGTS: 'Agents',
  AMP: 'Amplitude',
  AMT: 'Amount',
  ANGLE: 'Angle',
  ASPD: 'Animation speed',
  AUTO: 'Auto',
  BEATS: 'Beats',
  BITS: 'Bit depth',
  'BL.O': 'Blue offset',
  'BL.X': 'Blue X',
  'BL.Y': 'Blue Y',
  BLEED: 'Bleed',
  BLEND: 'Blend',
  BLK: 'Block size',
  BLKSZ: 'Block size',
  BLOBS: 'Max blobs',
  BLOOM: 'Bloom',
  BLUR: 'Blur',
  BRST: 'Burst',
  BRT: 'Brightness',
  BTHR: 'Brightness threshold',
  CAUST: 'Caustics',
  CELL: 'Cell size',
  CELLS: 'Cell count',
  CHAN: 'Channel',
  CHAOS: 'Chaos',
  CHARS: 'Character set',
  CHNC: 'Chance',
  CHRM: 'Chrome',
  'CN.X': 'Center X',
  'CN.Y': 'Center Y',
  CNT: 'Count',
  COLOR: 'Color mode',
  COLR: 'Color',
  CONF: 'Detection confidence',
  CONN: 'Connections',
  CONT: 'Contrast',
  COV: 'Coverage',
  CPS: 'Copies',
  CRUSH: 'Crush',
  CSHIFT: 'Color shift',
  CURVE: 'Curve',
  DCAY: 'Decay',
  DECAY: 'Decay',
  DEN: 'Density',
  DENS: 'Density',
  DEP: 'Deposit',
  DEPTH: 'Depth',
  DESAT: 'Desaturate',
  DET: 'Detection interval',
  DIR: 'Direction',
  DIST: 'Distance',
  DLY: 'Delay',
  DOT: 'Dot size',
  DPTH: 'Depth',
  DRIFT: 'Drift',
  DRIVE: 'Drive',
  EDGE: 'Edge',
  EDIST: 'Edge distortion',
  EMO: 'Emotion',
  FACE: 'Max faces',
  FADE: 'Fade',
  FDBK: 'Feedback',
  FEED: 'Feed rate',
  FILL: 'Fill mode',
  FILTER: 'Filter cutoff',
  FINT: 'Fresnel',
  FLASH: 'Flash',
  FLCK: 'Flicker',
  FLICK: 'Flicker speed',
  FLOW: 'Flow speed',
  FREQ: 'Frequency',
  FRMS: 'Frames',
  FRNB: 'Fresnel rainbow',
  FRNG: 'Fresnel rings',
  FTHR: 'Feather',
  'G.SZ': 'Glow size',
  GAIN: 'Gain',
  GLOW: 'Glow',
  'GM.B': 'Blue gamma',
  'GM.G': 'Green gamma',
  'GM.R': 'Red gamma',
  'GN.B': 'Blue gain',
  'GN.G': 'Green gain',
  'GN.R': 'Red gain',
  'GN.X': 'Green X',
  'GN.Y': 'Green Y',
  GRAD: 'Gradient fill',
  GRAIN: 'Grain',
  GRID: 'Grid size',
  HALO: 'Halo size',
  HAND: 'Max hands',
  HAZE: 'Haze',
  HDSW: 'Head switch noise',
  HUE: 'Hue shift',
  HUER: 'Hue range',
  ICONS: 'Icon set',
  INT: 'Intensity',
  INVERT: 'Invert',
  INVP: 'Invert chance',
  ITER: 'Iterations',
  JITR: 'Jitter',
  JITTER: 'Jitter',
  KFCH: 'Keyframe chance',
  KILL: 'Kill rate',
  'LF.B': 'Blue lift',
  'LF.G': 'Green lift',
  'LF.R': 'Red lift',
  LINES: 'Lines',
  LUMA: 'Luma bias',
  LVL: 'Levels',
  'MASK VIEW': 'Mask view',
  MAX: 'Max block',
  MDEN: 'Matrix density',
  MIN: 'Min block',
  MIX: 'Mix',
  MNSZ: 'Min size',
  MODE: 'Mode',
  MOSAIC: 'Mosaic fill',
  'MOT ONLY': 'Motion only',
  MSPD: 'Matrix speed',
  MTRL: 'Matrix trail',
  'N.SCALE': 'Noise scale',
  'N.SPD': 'Noise speed',
  NOISE: 'Noise',
  'OF.X': 'Offset X',
  'OF.Y': 'Offset Y',
  OFF: 'Offset',
  OFFSET: 'Byte offset',
  OFFX: 'Offset X',
  OFFY: 'Offset Y',
  OMIX: 'Original mix',
  OPAC: 'Opacity',
  PARA: 'Parallax',
  PERSP: 'Perspective',
  PHOS: 'Phosphor glow',
  PING: 'Ping',
  PLTE: 'Palette',
  POS: 'Position',
  PSTL: 'Pastel',
  PULSE: 'Pulse speed',
  RAD: 'Radius',
  RAG: 'Raggedness',
  RAINBW: 'Rainbow fill',
  RAND: 'Randomness',
  RANGE: 'Color range',
  RATE: 'Sample rate',
  RBIAS: 'Red bias',
  'RD.O': 'Red offset',
  'RD.X': 'Red X',
  'RD.Y': 'Red Y',
  REACH: 'Reach',
  RES: 'Resolution',
  RESD: 'Downscale',
  RESP: 'Response',
  RFSH: 'Refresh',
  RING: 'Ring width',
  ROT: 'Rotation',
  'ROT.X': 'Rotate X',
  'ROT.Y': 'Rotate Y',
  RVDUR: 'Reveal duration',
  SANG: 'Sensor angle',
  SAT: 'Saturation',
  'SAT+': 'Saturation boost',
  SATD: 'Saturation decay',
  SCALE: 'Scale',
  SCAN: 'Scan lines',
  'SCL.X': 'Scale X',
  'SCL.Y': 'Scale Y',
  SCTR: 'Scatter',
  SDST: 'Sensor distance',
  SEED: 'Seed',
  SEG: 'Segments',
  SENS: 'Sensitivity',
  SHADE: 'Shading',
  SHAPE: 'Shape',
  SHMR: 'Shimmer',
  SHOW: 'Show',
  SHTR: 'Shatter',
  SIZE: 'Size',
  SMIN: 'Min saturation',
  SMTH: 'Smoothing',
  SOFT: 'Softness',
  SOLID: 'Solid fill',
  SPD: 'Speed',
  SPIN: 'Spin',
  SQZ: 'Squeeze',
  STGS: 'Decay stages',
  STR: 'Strength',
  STRK: 'Streak',
  STRUCT: 'Structure',
  SVAR: 'Size variation',
  TARGET: 'Target',
  TDCY: 'Trail decay',
  TEAR: 'Tear',
  THICK: 'Thickness',
  THR: 'Threshold',
  THRSH: 'Threshold',
  TILT: 'Tilt',
  TINT: 'Tint',
  TMODE: 'Tint mode',
  TRAIL: 'Trail length',
  TRCK: 'Tracking confidence',
  TSNS: 'Trace sensitivity',
  TSPD: 'Tear speed',
  VIG: 'Vignette',
  VSHP: 'Vignette shape',
  WARP: 'Warp',
  WIDTH: 'Width',
  WIRE: 'Wireframe',
  ZEBRA: 'Zebra fill',
  ZOOM: 'Zoom',
}

/** Per-param names, keyed `effectId.paramId`, where a code means something different in that effect. */
export const PARAM_NAME_OVERRIDES: Record<string, string> = {
  'motion_extract.amplify': 'Amplify',
  'seg_matter.autoReshuffle': 'Auto reshuffle',
  'seg_matter.reshuffleBeats': 'Reshuffle beats',
  'seg_stale.autoBurst': 'Auto burst',
  'seg_stale.burstBeats': 'Burst beats',
  'seg_matter.wBlack': 'Black fill',
  'vhs.colorBleed': 'Color bleed',
  'point_cloud.depthChannel': 'Depth channel',
  'scan_lines.lineCount': 'Line count',
  'acid_slice.sliceCount': 'Slice count',
  'strand_path.particleCount': 'Particles',
  'strand_umbilical.tendrilCount': 'Tendrils',
  'face_hud.hudColor': 'HUD color',
  'datamosh.colorCorrupt': 'Color corruption',
  'reaction_diffusion.colorize': 'Colorize',
  'lens.curvature': 'Curvature',
  'feedback.decayCurve': 'Decay curve',
  'echo_trail.decayCurve': 'Decay curve',
  'dither.colorDepth': 'Color depth',
  'acid_cloud.depthScale': 'Depth scale',
  'strand_voidout.distortAmount': 'Distortion',
  'posterize.edgeContrast': 'Edge contrast',
  'strand_bridge.edgeSensitivity': 'Edge sensitivity',
  'contour.fadeMode': 'Fade mode',
  'strand_handprints.fadeSpeed': 'Fade speed',
  'seg_torn.fill': 'Fill',
  'echo_trail.hueAmount': 'Hue',
  'freeze_mask.invertMask': 'Invert mask',
  'landmarks.currentMode': 'Mode',
  'static_displace.noiseType': 'Noise type',
  'point_cloud.noiseDisplace': 'Noise displace',
  'scan_lines.lineOpacity': 'Line opacity',
  'chromatic.radialAmount': 'Radial',
  'echo_trail.trailRotation': 'Trail rotation',
  'posterize.saturationBoost': 'Saturation boost',
  'acid_voronoi.seedMode': 'Seed mode',
  'reaction_diffusion.seedAmt': 'Seed amount',
  'motion_extract.showOriginal': 'Show original',
  'freeze_mask.showFreeze': 'Show freeze',
  'block_displace.blockSize': 'Block size',
  'pixelate.pixelSize': 'Pixel size',
  'ascii.fontSize': 'Font size',
  'data_overlay.fontSize': 'Font size',
  'stipple.particleSize': 'Dot size',
  'track_bright.minSize': 'Min size',
  'track_edge.minSize': 'Min size',
  'track_color.minSize': 'Min size',
  'track_motion.minSize': 'Min size',
  'track_face.minSize': 'Min size',
  'track_hands.minSize': 'Min size',
  'acid_dots.dotScale': 'Dot scale',
  'point_cloud.pointSize': 'Point size',
  'strand_tar.spreadSpeed': 'Spread speed',
  'strand_odradek.sweepSpeed': 'Sweep speed',
  'strand_extinction.erosionSpeed': 'Erosion speed',
  'freeze_mask.updateSpeed': 'Update speed',
  'strand_timefall.streakCount': 'Streaks',
  'pixelSort.streakLength': 'Streak length',
  'freeze_mask.freezeThreshold': 'Freeze threshold',
  'strand_bbpod.tintStrength': 'Tint',
  'acid_contour.lineWidth': 'Line width',
  'acid_thgrid.lineWidth': 'Line width',
  'strand_seam.riftWidth': 'Rift width',
  'echo_trail.trailZoom': 'Trail zoom',
  'contour.trailLength': 'Trail length',
  'acid_scan.trail': 'Trail',
  'strand_bbpod.vignetteSize': 'Vignette',
  'dreamcore.radius': 'Glow radius',
  'feedback.edgeGlow': 'Edge glow',
  'crystallize.edgeGlow': 'Edge glow',
  'track_bright.boxFilterIntensity': 'Box filter',
  'track_edge.boxFilterIntensity': 'Box filter',
  'track_color.boxFilterIntensity': 'Box filter',
  'track_motion.boxFilterIntensity': 'Box filter',
  'track_face.boxFilterIntensity': 'Box filter',
  'track_hands.boxFilterIntensity': 'Box filter',
  'halation.radius': 'Glow radius',
}

/**
 * Status-bar descriptions for overridden params, keyed `effectId.paramId`. An overridden param never borrows the
 * shared code's PARAM_DESCRIPTIONS text (that text was written for another effect); without an entry here it shows
 * its name alone.
 */
export const PARAM_DESCRIPTION_OVERRIDES: Record<string, string> = {
  'chromatic.radialAmount': 'Radial vs linear aberration',
  'lens.curvature': 'Lens curvature distortion',
  'dither.colorDepth': 'Number of color levels per channel',
  'posterize.saturationBoost': 'Extra saturation after posterizing',
  'posterize.edgeContrast': 'Contrast boost along edges',
  'feedback.decayCurve': 'Shape of the fade between feedback frames',
  'echo_trail.decayCurve': 'Shape of the fade across the echoes',
  'echo_trail.trailZoom': 'Zoom applied to each echo',
  'echo_trail.trailRotation': 'Rotation applied to each echo',
  'feedback.edgeGlow': 'Glow along edges in the feedback',
  'crystallize.edgeGlow': 'Glow along the crystal cell edges',
  'halation.radius': 'Spread of the glow around highlights',
  'dreamcore.radius': 'Spread of the soft glow',
  'motion_extract.amplify': 'Boosts the difference between frames',
  'motion_extract.showOriginal': 'Show the original image under the motion',
  'strand_voidout.distortAmount': 'How far the ring pushes pixels outward',
  'reaction_diffusion.colorize': 'Blend of the simulation colors over the source',
  'block_displace.blockSize': 'Size of the displaced blocks',
  'pixelate.pixelSize': 'Size of each pixel block',
  'ascii.fontSize': 'Character size',
  'data_overlay.fontSize': 'Text size',
  'scan_lines.lineCount': 'Number of scan lines',
  'scan_lines.lineOpacity': 'Opacity of the scan lines',
  'acid_slice.sliceCount': 'Number of slices',
  'strand_path.particleCount': 'Number of particles',
  'strand_umbilical.tendrilCount': 'Number of tendrils',
  'strand_timefall.streakCount': 'Number of streaks',
  'pixelSort.streakLength': 'Length of the sorted streaks',
  'track_bright.boxFilterIntensity': 'Strength of the filter inside each tracked box',
  'track_edge.boxFilterIntensity': 'Strength of the filter inside each tracked box',
  'track_color.boxFilterIntensity': 'Strength of the filter inside each tracked box',
  'track_motion.boxFilterIntensity': 'Strength of the filter inside each tracked box',
  'track_face.boxFilterIntensity': 'Strength of the filter inside each tracked box',
  'track_hands.boxFilterIntensity': 'Strength of the filter inside each tracked box',
}

/** Shorter names for the 50px device dials, keyed by the full display name (used only when `short` is asked for). */
export const SHORT_NAMES: Record<string, string> = {
  Accumulation: 'Accumulate',
  'Animation speed': 'Anim speed',
  'Brightness threshold': 'Threshold',
  'Character set': 'Characters',
  'Detection confidence': 'Detection',
  'Tracking confidence': 'Tracking',
  'Detection interval': 'Interval',
  Connections: 'Links',
  'Color corruption': 'Corrupt',
  'Edge distortion': 'Distortion',
  'Edge contrast': 'Edges',
  'Edge sensitivity': 'Edges',
  'Filter cutoff': 'Cutoff',
  'Flicker speed': 'Flicker',
  'Fresnel rainbow': 'Rainbow',
  'Fresnel rings': 'Rings',
  'Head switch noise': 'Head noise',
  'Keyframe chance': 'Keyframes',
  'Matrix density': 'Density',
  'Matrix speed': 'Speed',
  'Matrix trail': 'Trail',
  'Noise displace': 'Displace',
  'Original mix': 'Original',
  'Line opacity': 'Opacity',
  'Phosphor glow': 'Phosphor',
  'Pulse speed': 'Pulse',
  'Reveal duration': 'Reveal',
  'Sensor angle': 'Angle',
  'Sensor distance': 'Distance',
  'Saturation boost': 'Saturate',
  'Saturation decay': 'Sat decay',
  'Size variation': 'Variation',
  'Trace sensitivity': 'Trace',
  'Trail rotation': 'Rotation',
  'Trail length': 'Trail',
  'Trail decay': 'Trail fade',
  'Vignette shape': 'Shape',
  'Reshuffle beats': 'Beats',
  'Burst beats': 'Beats',
  'Gradient fill': 'Gradient',
  'Rainbow fill': 'Rainbow',
  'Mosaic fill': 'Mosaic',
  'Spread speed': 'Spread',
  'Erosion speed': 'Erosion',
  'Update speed': 'Update',
  'Streak length': 'Length',
  'Freeze threshold': 'Threshold',
  'Min saturation': 'Min sat',
  'Decay stages': 'Stages',
  'Seed amount': 'Seed',
  'Blue offset': 'Blue off.',
  'Green gamma': 'Green gam.',
  'Noise scale': 'Noise size',
  'Noise speed': 'Noise rate',
  'Byte offset': 'Byte off.',
  Sensitivity: 'Sensitive',
  Perspective: 'Persp.',
  'Color bleed': 'Bleed',
  'Color depth': 'Colors',
  'Decay curve': 'Curve',
  'Color range': 'Range',
  'Slice count': 'Slices',
  'Line count': 'Lines',
  'Depth scale': 'Depth',
  'Sweep speed': 'Sweep',
  'Sample rate': 'Rate',
  'Glow radius': 'Radius',
  'Invert chance': 'Inv. chance',
}

const sentence = (s: string) => s.charAt(0).toUpperCase() + s.slice(1).toLowerCase()

/** camelCase / snake_case id -> sentence case words ("noiseSpeed" -> "Noise speed"). Short ids (x, y) are not humanised. */
function humaniseId(id: string): string | null {
  if (id.length < 3) return null
  const words = id.replace(/_/g, ' ').replace(/([a-z0-9])([A-Z])/g, '$1 $2').trim()
  return sentence(words)
}

const cache = new Map<string, string>()

/** Select option labels that are all-caps words read better in sentence case; real acronyms stay. */
const OPTION_NAMES: Record<string, string> = { NIGHTVIS: 'Night vision' }
const ACRONYMS = new Set(['RGB', 'HSL', 'CMYK', 'ASCII', 'HUD', 'LED', 'CRT', 'VHS'])

export function displayOptionLabel(label: string): string {
  if (OPTION_NAMES[label]) return OPTION_NAMES[label]
  if (!/^[A-Z][A-Z ]+$/.test(label) || ACRONYMS.has(label)) return label
  return sentence(label)
}

export function displayParamLabel(
  effectId: string,
  param: { id: string; label: string },
  opts?: { short?: boolean },
): string {
  const key = `${effectId}.${param.id}|${param.label}|${opts?.short ? 's' : ''}`
  const hit = cache.get(key)
  if (hit !== undefined) return hit
  const full = PARAM_NAME_OVERRIDES[`${effectId}.${param.id}`]
    ?? ABBREVIATIONS[param.label]
    ?? humaniseId(param.id)
    ?? sentence(param.label)
  const out = opts?.short ? SHORT_NAMES[full] ?? full : full
  cache.set(key, out)
  return out
}

/** Status-bar text for a param control: its full name plus the shared description (or how to use it). */
const statusCache = new Map<string, string>()

export function paramStatusText(effectId: string, param: { id: string; label: string }): string {
  const key = `${effectId}.${param.id}|${param.label}`
  const hit = statusCache.get(key)
  if (hit !== undefined) return hit
  const name = displayParamLabel(effectId, param)
  const k = `${effectId}.${param.id}`
  let what: string | null
  if (PARAM_NAME_OVERRIDES[k] !== undefined) {
    // An overridden name means the shared code means something else here: never borrow its description
    what = PARAM_DESCRIPTION_OVERRIDES[k] ?? null
  } else {
    const desc = PARAM_DESCRIPTIONS[param.label]
    const i = desc ? desc.indexOf(': ') : -1
    what = desc ? (i >= 0 ? desc.slice(i + 2) : desc) : null
  }
  const out = what ? `${name}: ${what}. Drag to change, double-click to reset` : `${name}. Drag to change, double-click to reset`
  statusCache.set(key, out)
  return out
}
